-- MySQL Script generated by MySQL Workbench
-- Sun May 20 20:39:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `correoUsuario` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`correoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `rfc` VARCHAR(10) NOT NULL,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `Usuario_correoUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`rfc`, `Usuario_correoUsuario`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_correoUsuario`)
    REFERENCES `mydb`.`Usuario` (`correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Usuario1_idx` ON `mydb`.`Cliente` (`Usuario_correoUsuario` ASC);

CREATE UNIQUE INDEX `Usuario_correoUsuario_UNIQUE` ON `mydb`.`Cliente` (`Usuario_correoUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `nomPedido` INT NOT NULL,
  `fechaPedido` DATE NOT NULL,
  `precioTotal` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  `Cliente_rfc` VARCHAR(10) NOT NULL,
  `Cliente_Usuario_correoUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`nomPedido`, `Cliente_rfc`, `Cliente_Usuario_correoUsuario`),
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_rfc` , `Cliente_Usuario_correoUsuario`)
    REFERENCES `mydb`.`Cliente` (`rfc` , `Usuario_correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iva_UNIQUE` ON `mydb`.`Pedido` (`iva` ASC);

CREATE INDEX `fk_Pedido_Cliente1_idx` ON `mydb`.`Pedido` (`Cliente_rfc` ASC, `Cliente_Usuario_correoUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `numFactura` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` DATE NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `comentarios` MEDIUMTEXT NULL,
  `Pedido_nomPedido` INT NOT NULL,
  PRIMARY KEY (`numFactura`, `Pedido_nomPedido`),
  CONSTRAINT `fk_Factura_Pedido1`
    FOREIGN KEY (`Pedido_nomPedido`)
    REFERENCES `mydb`.`Pedido` (`nomPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_Pedido1_idx` ON `mydb`.`Factura` (`Pedido_nomPedido` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administradores` (
  `numPersonal` VARCHAR(10) NOT NULL,
  `nombreCompleto` VARCHAR(60) NOT NULL,
  `correoElectronico` VARCHAR(60) NOT NULL,
  `Usuario_correoUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`numPersonal`, `Usuario_correoUsuario`),
  CONSTRAINT `fk_Administradores_Usuario1`
    FOREIGN KEY (`Usuario_correoUsuario`)
    REFERENCES `mydb`.`Usuario` (`correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Administradores_Usuario1_idx` ON `mydb`.`Administradores` (`Usuario_correoUsuario` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bodega` (
  `idBodega` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `Administradores_numPersonal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idBodega`, `Administradores_numPersonal`),
  CONSTRAINT `fk_Bodega_Administradores1`
    FOREIGN KEY (`Administradores_numPersonal`)
    REFERENCES `mydb`.`Administradores` (`numPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Bodega_Administradores1_idx` ON `mydb`.`Bodega` (`Administradores_numPersonal` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vehiculo` (
  `numMotor` INT NOT NULL,
  `matricula` VARCHAR(7) NOT NULL,
  `modelo` VARCHAR(10) NOT NULL,
  `kilometraje` FLOAT NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `numPasajeos` INT NOT NULL,
  `numCilindros` INT NOT NULL,
  `Pedido_nomPedido` INT NOT NULL,
  `Bodega_idBodega` INT NOT NULL,
  PRIMARY KEY (`numMotor`, `Pedido_nomPedido`, `Bodega_idBodega`),
  CONSTRAINT `fk_Vehiculo_Pedido1`
    FOREIGN KEY (`Pedido_nomPedido`)
    REFERENCES `mydb`.`Pedido` (`nomPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Bodega1`
    FOREIGN KEY (`Bodega_idBodega`)
    REFERENCES `mydb`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vehiculo_Pedido1_idx` ON `mydb`.`Vehiculo` (`Pedido_nomPedido` ASC);

CREATE INDEX `fk_Vehiculo_Bodega1_idx` ON `mydb`.`Vehiculo` (`Bodega_idBodega` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
