-- MySQL Script generated by MySQL Workbench
-- Wed May 23 00:19:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rentabd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rentabd` ;

-- -----------------------------------------------------
-- Schema rentabd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rentabd` DEFAULT CHARACTER SET utf8 ;
USE `rentabd` ;

-- -----------------------------------------------------
-- Table `rentabd`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Usuarios` (
  `correoUsuario` VARCHAR(60) NOT NULL,
  `contraseña` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`correoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rentabd`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Clientes` (
  `rfc` VARCHAR(10) NOT NULL,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `Usuarios_correoUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`rfc`),
  CONSTRAINT `fk_Clientes_Usuarios1`
    FOREIGN KEY (`Usuarios_correoUsuario`)
    REFERENCES `rentabd`.`Usuarios` (`correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Clientes_Usuarios1_idx` ON `rentabd`.`Clientes` (`Usuarios_correoUsuario` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Pedidos` (
  `nomPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaPedido` DATE NOT NULL,
  `precioTotal` FLOAT NOT NULL,
  `iva` FLOAT NOT NULL,
  `Clientes_rfc` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nomPedido`),
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_rfc`)
    REFERENCES `rentabd`.`Clientes` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Clientes1_idx` ON `rentabd`.`Pedidos` (`Clientes_rfc` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Facturas` (
  `numFactura` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` DATE NOT NULL,
  `fechaVencimiento` DATE NOT NULL,
  `comentarios` MEDIUMTEXT NULL,
  `Pedido_nomPedido` INT NOT NULL,
  PRIMARY KEY (`numFactura`),
  CONSTRAINT `fk_Factura_Pedido`
    FOREIGN KEY (`Pedido_nomPedido`)
    REFERENCES `rentabd`.`Pedidos` (`nomPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Factura_Pedido_idx` ON `rentabd`.`Facturas` (`Pedido_nomPedido` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Administradores` (
  `numPersonal` VARCHAR(10) NOT NULL,
  `nombreCompleto` VARCHAR(60) NOT NULL,
  `correoElectronico` VARCHAR(60) NOT NULL,
  `Usuarios_correoUsuario` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`numPersonal`),
  CONSTRAINT `fk_Administradores_Usuarios1`
    FOREIGN KEY (`Usuarios_correoUsuario`)
    REFERENCES `rentabd`.`Usuarios` (`correoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Administradores_Usuarios1_idx` ON `rentabd`.`Administradores` (`Usuarios_correoUsuario` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Bodegas` (
  `idBodega` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(70) NOT NULL,
  `Administradores_numPersonal` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idBodega`),
  CONSTRAINT `fk_Bodegas_Administradores1`
    FOREIGN KEY (`Administradores_numPersonal`)
    REFERENCES `rentabd`.`Administradores` (`numPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Bodegas_Administradores1_idx` ON `rentabd`.`Bodegas` (`Administradores_numPersonal` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Vehiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Vehiculos` (
  `numMotor` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(7) NOT NULL,
  `modelo` VARCHAR(10) NOT NULL,
  `kilometraje` FLOAT NOT NULL,
  `marca` VARCHAR(20) NOT NULL,
  `color` VARCHAR(15) NOT NULL,
  `numPasajeos` INT NOT NULL,
  `numCilindros` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `Pedidos_nomPedido` INT NOT NULL,
  `Bodegas_idBodega` INT NOT NULL,
  PRIMARY KEY (`numMotor`),
  CONSTRAINT `fk_Vehiculos_Pedidos1`
    FOREIGN KEY (`Pedidos_nomPedido`)
    REFERENCES `rentabd`.`Pedidos` (`nomPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculos_Bodegas1`
    FOREIGN KEY (`Bodegas_idBodega`)
    REFERENCES `rentabd`.`Bodegas` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Vehiculos_Pedidos1_idx` ON `rentabd`.`Vehiculos` (`Pedidos_nomPedido` ASC);

CREATE INDEX `fk_Vehiculos_Bodegas1_idx` ON `rentabd`.`Vehiculos` (`Bodegas_idBodega` ASC);


-- -----------------------------------------------------
-- Table `rentabd`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rentabd`.`Telefonos` (
  `idTelefonos` INT NOT NULL AUTO_INCREMENT,
  `numeroTelefono` VARCHAR(45) NOT NULL,
  `Clientes_rfc` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTelefonos`),
  CONSTRAINT `fk_Telefonos_Clientes1`
    FOREIGN KEY (`Clientes_rfc`)
    REFERENCES `rentabd`.`Clientes` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Telefonos_Clientes1_idx` ON `rentabd`.`Telefonos` (`Clientes_rfc` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
